export const ALREADY_USER_ERROR = 'User is already registered'
export const USER_NOT_FOUND = 'User is not found'
export const USER_WRONG_PASSWORD = 'password is wrong'
export const LOGIN_ERROR = 'Login was not successfully, wrong credentials'
export const JWT_DENIED = 'JWT_DENIED'
export const COOKIE_DENIED = 'COOKIE_DENIED'
export const ACCESS_DENIED = 'Access Denied'
